### PR TITLE
Add llsc_assume external function

### PR DESCRIPTION
**Pull request by Kuigesi**
Add llvm.va_copy intrinsic
Add support for Packed struct
Fix: fix error in parsing llvm string, replace all un-printable symbol
Fix: rewrite visitTypeConstList in tail-recursive way (more efficient in dealing with large const array, avoid stack over flow)
Fix: handle store instruction with no alignment.

### CODE REVIEW

**Comment by Tantalus13A98B5F** [comment]
Why do we need `PackedStructCalc`? IIRC we don't have to care about alignment in packed struct?

**Comment by Kuigesi** [comment]
> Why do we need `PackedStructCalc`? IIRC we don't have to care about alignment in packed struct?

**Comment by Kuigesi** [comment]
> Why do we need `PackedStructCalc`? IIRC we don't have to care about alignment in packed struct?

Yes, we do not, I am just copying StructCalc so that the code look similar.

**Comment by Kuigesi** [comment]
> > Why do we need `PackedStructCalc`? IIRC we don't have to care about alignment in packed struct?
> 
> Yes, we do not, I am just copying StructCalc so that the code look similar. PackedStruct perform no padding.

**Comment by Tantalus13A98B5F** [comment]
I see. But anyway, `StructCalc` is not a great source for copying - from where I am it is somewhat twisted, and as there is no actual padding in `PackedStruct` it can be a lot simpler.

**Comment by Kuigesi** [comment]
> I see. But anyway, `StructCalc` is not a great source for copying - from where I am it is somewhat twisted, and as there is no actual padding in `PackedStruct` it can be a lot simpler.

I see that, the padding in PackedStructClac is just zero, I will refactore it make it simpler, Thx.

**Pull request merged**
