### PR TITLE
fixed llvm null mapping

### PR DESCRIPTION
**Pull request by PROgram52bc**

### CODE REVIEW

**Comment by Shangyint** [comment]
Two additional comments here:
1. The `get_bw` method in `LocV` does not need change. At the beginning of `int_op_2`, `LocV` is converted to `IntV`.
2. It would be better if you designate another address for NULL, because in fact 0 is a valid address in our system.

Also, you can also add the relevant test case.

**Comment by Kraks** [comment]
If you test with ptrpred.c, I think it is likely to produce an incorrect result since malloc may return 0. -1 seems to make more sense.

**Comment by Kraks** [comment]
> > It looks good to me. Have you tried it on the ptrpred.c test case?
> 
> I tested it, and there is one path explored without errors thrown. Is that a good indication?

You probably also need to check if the taken path is indeed the correct one.

**Comment by PROgram52bc** [comment]
For this llvm code snippet
```llvm
if.then:                                          ; preds = %entry
  %call = call i8* @malloc(i64 4)
  %0 = bitcast i8* %call to i32*
  store i32* %0, i32** %b, align 8
  %1 = load i32*, i32** %b, align 8
  %tobool1 = icmp ne i32* %1, null
  br i1 %tobool1, label %if.then2, label %if.end

if.then2:                                         ; preds = %if.then
  store i32 1, i32* %retval, align 4
  br label %return

if.end:                                           ; preds = %if.then
  store i32 2, i32* %retval, align 4
  br label %return

if.else:                                          ; preds = %entry
  store i32 3, i32* %retval, align 4
  br label %return
```
I added print statements in the instrumented `llsc_main.cpp`, and got the following output
```
entry;[
0s/0s] #blocks: 1/6; #paths: 1; #threads: 1; #async created: 0; #queries: 0/0
if.then;
memLoc: LocV(0)
bytes: 4
if.then2;
return;
[0s/0s] #blocks: 4/6; #paths: 1; 
```
Seems like the `if.then2` branch is taken, corresponding to the `return 1` branch.

**Comment by Kraks** [comment]
Looks like this PR is subsumed by https://github.com/Kraks/sai/pull/21, close this one?

**Pull request closed without merging**
