### PR TITLE
fix BenchLLSC: pass Seq[String] as cmd line argument

### PR DESCRIPTION
**Pull request by Kuigesi**

### CODE REVIEW

**Comment by Tantalus13A98B5F** [comment]
Thanks! I wonder is there any new case requiring `cliArgOpt` to be `Seq[String]`?

**Comment by Kuigesi** [comment]
> Thanks! I wonder is there any new case requiring `cliArgOpt` to be `Seq[String]`?

I checked that, I think there are only three places and we covered them all.

**Comment by Tantalus13A98B5F** [comment]
ah, I mean, why do we want to use `Seq[String]`?

**Comment by Kuigesi** [comment]
> ah, I mean, why do we want to use `Seq[String]`?

yes. For coreutils programs, the executing command will be like ./PureLLSC_echo_linked_posix --cons-indep --argv="./echo.bc --sym-stdout -sym-arg 3"

If we pass the argument using String, scala's Process will first split the argument with space. --argv="./echo.bc --sym-stdout -sym-arg 3" will be breaked into several arguments.

**Pull request merged**
